version: '3.7'
services:
  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:0.4.7
    ports:
      - '8082:8082'
    environment:
      SERVER_PORT: 8082
      JSON_CONFIG: >
        {
            "interactiveLogin": true,
            "httpServer": "NettyWrapper",
            "tokenCallbacks": [
                {
                    "issuerId": "local-tokenx",
                    "tokenExpiry": 31536000,
                    "requestMappings": [
                        {
                            "requestParam": "scope",
                            "match": "*",
                            "claims": {
                                "pid": "123456789",
                                "aud": "somescope"
                            }
                        }
                    ]
                }
            ]
        }